FROM localhost/securetty_base:latest

ARG QUARANTINE_DAYS=7
COPY install.sh /tmp/install.sh
RUN chmod +x /tmp/install.sh && /tmp/install.sh && rm /tmp/install.sh

RUN groupadd -g 1000 omniroute \
    && useradd -u 1000 -g 1000 -m -s /bin/bash omniroute \
    && mkdir -p /data && chown omniroute:omniroute /data

USER omniroute
WORKDIR /data

EXPOSE 4000

CMD ["omniroute", "serve", "--port", "4000", "--no-open"]
