FROM localhost/securetty_base:latest

RUN python3.12 -m pip install --break-system-packages \
        fastmcp uvicorn httpx requests aiohttp

RUN groupadd -g {{ securetty_uid }} mcp \
    && useradd -u {{ securetty_uid }} -g {{ securetty_gid }} -m -s /bin/bash mcp

USER mcp
WORKDIR /mcp

CMD ["python3.12", "-m", "uvicorn"]
