FROM localhost/securetty_base:latest

ARG QUARANTINE_DAYS={{ securetty_quarantine_days }}
COPY install.sh /tmp/install.sh
RUN chmod +x /tmp/install.sh && QUARANTINE_DAYS=${QUARANTINE_DAYS} /tmp/install.sh && rm /tmp/install.sh

RUN groupadd -g {{ securetty_gid }} omniroute \
    && useradd -u {{ securetty_uid }} -g {{ securetty_gid }} -m -s /bin/bash omniroute \
    && mkdir -p /data && chown omniroute:omniroute /data

USER omniroute
WORKDIR /data

EXPOSE 4000

CMD ["omniroute", "serve", "--port", "4000", "--no-open"]
