FROM localhost/securetty_base:latest

COPY scripts/creds-server.py /usr/local/bin/creds-server.py
RUN chmod +x /usr/local/bin/creds-server.py

RUN groupadd -g 1000 creds \
    && useradd -u 1000 -g 1000 -m -s /bin/bash creds

USER creds
EXPOSE 8800

CMD ["python3.12", "/usr/local/bin/creds-server.py"]
