#!/bin/bash
# Generate provenance metadata for agent-produced CI artifacts (issue #99)
# Three output modes: --commit (git trailers), --comment (markdown footer), --artifact (JSON)
# Reads agent/model/session from env vars with CLI overrides.
set -euo pipefail

usage() {
    cat <<'EOF'
Usage: securetty-provenance.sh --commit|--comment|--artifact [OPTIONS]

Modes:
  --commit      Git trailer format (Assisted-by, Agent-Model, Agent-Session)
  --comment     Markdown footer for PR/MR comments
  --artifact    JSON provenance metadata for CI artifacts

Options:
  --agent NAME        Agent name (default: $SECURETTY_AGENT or "claude")
  --model MODEL       Model identifier (default: $CLAUDE_MODEL or "unknown")
  --session ID        Session identifier (default: $CLAUDE_SESSION_ID or "unknown")
  -h, --help          Show this help message
EOF
}

main() {
    local mode=""
    local agent="${SECURETTY_AGENT:-claude}"
    local model="${CLAUDE_MODEL:-unknown}"
    local session="${CLAUDE_SESSION_ID:-unknown}"

    while [ $# -gt 0 ]; do
        case "$1" in
            --commit)   mode="commit";  shift ;;
            --comment)  mode="comment"; shift ;;
            --artifact) mode="artifact"; shift ;;
            --agent)    agent="${2:?--agent requires a value}"; shift 2 ;;
            --model)    model="${2:?--model requires a value}"; shift 2 ;;
            --session)  session="${2:?--session requires a value}"; shift 2 ;;
            -h|--help)  usage; exit 0 ;;
            *)
                printf 'error: unknown option: %s\n' "$1" >&2
                usage >&2
                exit 1
                ;;
        esac
    done

    if [ -z "$mode" ]; then
        printf 'error: one of --commit, --comment, or --artifact is required\n' >&2
        usage >&2
        exit 1
    fi

    case "$mode" in
        commit)
            emit_commit "$agent" "$model" "$session"
            ;;
        comment)
            emit_comment "$agent" "$model" "$session"
            ;;
        artifact)
            emit_artifact "$agent" "$model" "$session"
            ;;
    esac
}

emit_commit() {
    local agent="$1" model="$2" session="$3"
    printf 'Assisted-by: %s (%s)\n' "$agent" "$model"
    printf 'Agent-Model: %s\n' "$model"
    if [ "$session" != "unknown" ]; then
        printf 'Agent-Session: %s\n' "$session"
    fi
}

emit_comment() {
    local agent="$1" model="$2" session="$3"
    printf -- '---\n'
    printf '_Generated by securetty | agent: %s | model: %s | session: %s_\n' \
        "$agent" "$model" "$session"
}

emit_artifact() {
    local agent="$1" model="$2" session="$3"
    local timestamp
    timestamp=$(date -u +%FT%TZ)
    printf '{"generator":"securetty","agent":"%s","model":"%s","session":"%s","timestamp":"%s"}\n' \
        "$agent" "$model" "$session" "$timestamp"
}

main "$@"
