#!/bin/bash
# Ansible managed
# Generate .env from current host environment + shell profile + pass store.
# Called before every container start — always fresh keys.


ENV_FILE="${1:-$(dirname "$0")/../.env}"

# Source profile scripts to populate env (best effort, ignore all errors)
(
    source "/home/daoneill/.bashrc" 2>/dev/null
    for f in "/home/daoneill/.bashrc.d/scripts.d/"*.sh; do
        source "$f" 2>/dev/null
    done

    # Resolve lazy-loaded secrets from pass/keyring
    type load-secrets &>/dev/null && load-secrets 2>/dev/null
    # Export discovered vars so parent can read them
    env
) > /run/user/1000/securetty-env-discovery 2>/dev/null || true


# Merge discovered vars into current env
while IFS='=' read -r key val; do
    [ -z "$key" ] && continue
    [[ "$key" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || continue
    export "$key=$val" 2>/dev/null || true
done < /run/user/1000/securetty-env-discovery
rm -f /run/user/1000/securetty-env-discovery


# Fallback: grep profile files for export VAR=value
grep_key() {
    local name="$1"
    grep -rhoPm1 "(?<=export ${name}=)['\"]?[^'\"#\n]+['\"]?" \
        "/home/daoneill/.bashrc" "/home/daoneill/.bashrc.d/" 2>/dev/null \
        | head -1 | tr -d "'" | tr -d '"' | xargs
}


# Get key: env first, grep fallback
get_key() {
    local name="$1"
    local val="${!name:-}"
    [ -n "$val" ] && echo "$val" && return
    val=$(grep_key "$name")
    [ -n "$val" ] && echo "$val" && return
    echo ""
}

# Get key from specific config file
get_config_key() {
    local file="$1" name="$2"
    grep -oP "(?<=${name}=).+" "$file" 2>/dev/null | head -1 || echo ""
}

# Vertex/Claude-specific vars
VERTEX_VARS=(
    CLAUDE_CODE_USE_VERTEX
    ANTHROPIC_VERTEX_PROJECT_ID
    GOOGLE_CLOUD_PROJECT
    GOOGLE_CLOUD_LOCATION
    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC
)

{

    echo "# Auto-generated by securetty — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "# Source: host environment + shell profile + pass store"
    echo "# Regenerated on every container start"
    echo ""

    # API keys from pass store
    KEYS=(
        AI_API_KEY
        GEMINI_API_KEY
        MISTRAL_API_KEY
        OPENROUTER_API_KEY
        GROQ_API_KEY
        CEREBRAS_API_KEY
        SAMBANOVA_API_KEY
        GITHUB_TOKEN
        OMNIROUTE_API_KEY
        OMNIROUTE_INITIAL_PASSWORD
        CLOUDFLARE_AI_TOKEN
        GITLAB_TOKEN
        JIRA_JPAT
        JIRA_URL
        JIRA_PROJECT_KEY
        JIRA_BOARD_ID
        JIRA_EMAIL
        JIRA_COMPONENT_NAME
        SLACK_HOST
        WORDPRESS_URL
        WORDPRESS_USERNAME
        WORDPRESS_PASSWORD
        WORDPRESS_APPLICATION
        OPENAI_API_KEY
        GITLAB_API_TOKEN
        JIRA_AI_API_KEY
    )


    found=0
    total=${#KEYS[@]}

    for key in "${KEYS[@]}"; do
        val=$(get_key "$key")
        echo "${key}=${val}"
        [ -n "$val" ] && found=$((found + 1))
    done

    # Static env vars (hardcoded config, not secrets)
    echo "JIRA_EPIC_FIELD=customfield_10014"
    echo "JIRA_EPIC_NAME_FIELD=customfield_10011"
    echo "JIRA_STORY_POINTS_FIELD=customfield_10028"
    echo "JIRA_SPRINT_FIELD=customfield_10020"
    echo "JIRA_ACCEPTANCE_CRITERIA_FIELD=customfield_10718"
    echo "JIRA_BLOCKED_FIELD=customfield_10517"
    echo "JIRA_BLOCKED_REASON_FIELD=customfield_10483"
    echo "JIRA_WORKSTREAM_FIELD=customfield_10681"
    echo "JIRA_WORKSTREAM_VALUE=Cloud Automation Analytics"
    echo "JIRA_PRIORITY=Normal"
    echo "JIRA_AFFECTS_VERSION=aa-latest"
    echo "JIRA_AI_PROVIDER=vertex"
    echo "JIRA_AI_MODEL=claude-sonnet-4-6@20250514"

    # Slack credentials (extracted fresh from Chrome on host — parsed, not eval'd)
    SLACK_CREDS_SCRIPT="/home/daoneill/src/agent-mcp-skills/slack/get-slack-creds"
    if [ -x "$SLACK_CREDS_SCRIPT" ]; then
        _slack_out=$("$SLACK_CREDS_SCRIPT" --quiet 2>/dev/null) || true
        _slack_xoxc=$(echo "$_slack_out" | grep -oP '(?<=SLACK_XOXC_TOKEN=")[^"]+' || true)
        _slack_cookie=$(echo "$_slack_out" | grep -oP '(?<=SLACK_D_COOKIE=")[^"]+' || true)
        [ -n "$_slack_xoxc" ] && echo "SLACK_XOXC_TOKEN=${_slack_xoxc}" && found=$((found + 1))
        [ -n "$_slack_cookie" ] && echo "SLACK_D_COOKIE=${_slack_cookie}" && found=$((found + 1))
    fi

    # Omniroute config file keys
    sek=$(get_config_key "/home/daoneill/.omniroute/.env" STORAGE_ENCRYPTION_KEY)

    echo "STORAGE_ENCRYPTION_KEY=${sek}"
    total=$((total + 1))
    [ -n "$sek" ] && found=$((found + 1))

    # Vertex/Claude vars (auto-discovered from env)
    echo ""
    echo "# Claude/Vertex (auto-discovered)"

    for key in "${VERTEX_VARS[@]}"; do
        val="${!key:-}"
        if [ -n "$val" ]; then
            echo "${key}=${val}"
            found=$((found + 1))
        fi
    done
    total=$((total + ${#VERTEX_VARS[@]}))

    # Any other CLAUDE_ vars in env
    while IFS='=' read -r key val; do
        [[ "$key" =~ ^CLAUDE ]] || continue
        # Skip ones already handled
        case "$key" in
            CLAUDE_CODE_USE_VERTEX) continue ;;
            CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC) continue ;;

        esac
        # Skip session-specific vars
        case "$key" in *SESSION*|*EXECPATH*|*ENTRYPOINT*) continue ;; esac
        echo "${key}=${val}"
    done < <(env | grep '^CLAUDE' | sort)

} > "$ENV_FILE"
chmod 0600 "$ENV_FILE"

# Generate per-service env files (least privilege -- each service gets only what it needs)
ENV_DIR="$(dirname "$ENV_FILE")"

# Omniroute: provider API keys + encryption key + Ollama endpoint
{
    grep -E '^AI_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^GEMINI_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^MISTRAL_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^OPENROUTER_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^GROQ_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^CEREBRAS_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^SAMBANOVA_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^OMNIROUTE_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^OMNIROUTE_INITIAL_PASSWORD=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^CLOUDFLARE_AI_TOKEN=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^GITLAB_TOKEN=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_JPAT=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_URL=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_PROJECT_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_BOARD_ID=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_EMAIL=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_COMPONENT_NAME=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^SLACK_HOST=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^WORDPRESS_URL=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^WORDPRESS_USERNAME=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^WORDPRESS_PASSWORD=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^WORDPRESS_APPLICATION=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^OPENAI_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^GITLAB_API_TOKEN=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^JIRA_AI_API_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^STORAGE_ENCRYPTION_KEY=' "$ENV_FILE" 2>/dev/null || true
    grep -E '^(CLAUDE_CODE_USE_VERTEX|ANTHROPIC_VERTEX_PROJECT_ID|GOOGLE_CLOUD_PROJECT|GOOGLE_CLOUD_LOCATION)=' "$ENV_FILE" 2>/dev/null || true
    echo "OLLAMA_HOST=http://ollama:11434"
    grep -E '^OMNIROUTE_INITIAL_PASSWORD=' "$ENV_FILE" 2>/dev/null || true

} > "$ENV_DIR/.env.omniroute"
chmod 0600 "$ENV_DIR/.env.omniroute"

# CloudCLI: Vertex/Anthropic config only
grep -E '^(CLAUDE_CODE_USE_VERTEX|ANTHROPIC_VERTEX_PROJECT_ID|GOOGLE_CLOUD_PROJECT|GOOGLE_CLOUD_LOCATION|CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC)=' \
    "$ENV_FILE" > "$ENV_DIR/.env.cloudcli" 2>/dev/null || true
chmod 0600 "$ENV_DIR/.env.cloudcli"

# Dev container: gets everything (agents need various keys)
# Uses the main .env file as-is

# MCP service env files (per-service secrets only)
# Jira
{
    grep -E '^(JIRA_JPAT|JIRA_URL|JIRA_PROJECT_KEY|JIRA_BOARD_ID|JIRA_EMAIL|JIRA_COMPONENT_NAME|JIRA_AI_API_KEY)=' "$ENV_FILE" 2>/dev/null || true
    echo "JIRA_EPIC_FIELD=customfield_10014"
    echo "JIRA_EPIC_NAME_FIELD=customfield_10011"
    echo "JIRA_STORY_POINTS_FIELD=customfield_10028"
    echo "JIRA_SPRINT_FIELD=customfield_10020"
    echo "JIRA_ACCEPTANCE_CRITERIA_FIELD=customfield_10718"
    echo "JIRA_BLOCKED_FIELD=customfield_10517"
    echo "JIRA_BLOCKED_REASON_FIELD=customfield_10483"
    echo "JIRA_WORKSTREAM_FIELD=customfield_10681"
    echo "JIRA_WORKSTREAM_VALUE=Cloud Automation Analytics"
    echo "JIRA_PRIORITY=Normal"
    echo "JIRA_AFFECTS_VERSION=aa-latest"
    echo "JIRA_AI_PROVIDER=vertex"
    echo "JIRA_AI_MODEL=claude-sonnet-4-6@20250514"
} > "$ENV_DIR/.env.mcp-jira"
chmod 0600 "$ENV_DIR/.env.mcp-jira"

# GitLab
grep -E '^GITLAB_TOKEN=' "$ENV_FILE" > "$ENV_DIR/.env.mcp-gitlab" 2>/dev/null || true
echo "GITLAB_URL=https://gitlab.cee.redhat.com" >> "$ENV_DIR/.env.mcp-gitlab"
chmod 0600 "$ENV_DIR/.env.mcp-gitlab"

# GitHub
grep -E '^GITHUB_TOKEN=' "$ENV_FILE" > "$ENV_DIR/.env.mcp-github" 2>/dev/null || true
chmod 0600 "$ENV_DIR/.env.mcp-github"

# Slack
grep -E '^(SLACK_XOXC_TOKEN|SLACK_D_COOKIE|SLACK_HOST|SLACK_ENTERPRISE_ID)=' "$ENV_FILE" > "$ENV_DIR/.env.mcp-slack" 2>/dev/null || true
chmod 0600 "$ENV_DIR/.env.mcp-slack"

# WordPress
grep -E '^WORDPRESS_' "$ENV_FILE" > "$ENV_DIR/.env.mcp-wordpress" 2>/dev/null || true
chmod 0600 "$ENV_DIR/.env.mcp-wordpress"

# Credential proxy (git tokens only)
grep -E '^(GITHUB_TOKEN|GITLAB_TOKEN)=' "$ENV_FILE" > "$ENV_DIR/.env.creds" 2>/dev/null || true
chmod 0600 "$ENV_DIR/.env.creds"


echo "Generated $ENV_FILE ($found/$total keys discovered)"
echo "  + .env.omniroute (provider keys only)"
echo "  + .env.cloudcli (Vertex/Anthropic only)"
echo "  + .env.mcp-jira (Jira secrets)"
echo "  + .env.mcp-gitlab (GitLab token)"
echo "  + .env.mcp-github (GitHub token)"
echo "  + .env.mcp-slack (Slack credentials)"
echo "  + .env.mcp-wordpress (WordPress credentials)"
echo "  + .env.creds (git tokens only)"
