#!/bin/bash
CERT_ARGS=""
[ -f /certs/client.crt ] && CERT_ARGS="--cert /certs/client.crt --key /certs/client.key --cacert /certs/ca.crt"
export GH_TOKEN=$(curl $CERT_ARGS -sf https://securetty-creds:8800/token/github 2>/dev/null)
export GITHUB_TOKEN="$GH_TOKEN"
exec /usr/local/bin/gh.real "$@"
