#!/bin/bash
# Load securetty egress nftables rules into rootless-netns
# Generated by ansible — do not edit

nft delete table inet securetty_egress 2>/dev/null
nft add table inet securetty_egress
nft "add set inet securetty_egress allowed_ipv4 { type ipv4_addr; flags interval; }"
nft "add chain inet securetty_egress forward { type filter hook forward priority -1; policy accept; }"
nft add rule inet securetty_egress forward ip saddr != 10.89.100.0/24 accept
nft add rule inet securetty_egress forward ip saddr 10.89.100.0/24 ip daddr 10.89.100.0/24 accept
nft "add rule inet securetty_egress forward ip saddr 10.89.100.0/24 ip daddr 10.89.100.1 meta l4proto { tcp, udp } th dport 53 accept"
nft add rule inet securetty_egress forward ip saddr 10.89.100.0/24 ip daddr 100.64.0.0/10 accept
nft add rule inet securetty_egress forward ip saddr 10.89.100.0/24 ip daddr @allowed_ipv4 accept
nft add rule inet securetty_egress forward ip saddr 10.89.100.0/24 ct state established,related accept
nft add rule inet securetty_egress forward ip saddr 10.89.100.0/24 counter drop
