FROM localhost/securetty_base:latest

RUN curl -fsSL https://ollama.com/install.sh | sh

RUN groupadd -g 1000 ollama \
    && useradd -u 1000 -g 1000 -m -s /bin/bash ollama \
    && mkdir -p /data/models && chown -R ollama:ollama /data

USER ollama
WORKDIR /data

ENV OLLAMA_MODELS=/data/models
ENV OLLAMA_HOST=0.0.0.0:11434

EXPOSE 11434

CMD ["ollama", "serve"]
